services:
  db:
    image: arm64v8/postgres:latest
    container_name: postgres_local
    command: -c 'max_connections=1000'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DATABASE: ktor
    shm_size: 1G
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - docker

  ktor:
    image: ktor:latest
    container_name: ktor
    ports:
      - "8081:8081"
    networks:
      - docker
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "8192M"

  webflux:
    image: webflux:latest
    container_name: webflux
    ports:
      - "8082:8082"
    networks:
      - docker
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "8192M"

  mvc:
    image: mvc:latest
    container_name: mvc
    ports:
      - "8083:8083"
    networks:
      - docker
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "8192M"

  httpbin:
    image: httpbin:latest
    container_name: httpbin
    ports:
      - "8084:8084"
    networks:
      - docker

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - docker

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
    networks:
      - docker
    volumes:
      - grafana_data:/var/lib/grafana
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml

networks:
  docker:
    driver: bridge

volumes:
  postgres_data:
  grafana_data:
