version: '3.8'

services:
  db:
    image: arm64v8/postgres:latest
    container_name: postgres_local
    command: -c 'max_connections=50000'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DATABASE: ktor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
